set(LICENSE_DESTINATION .)
set(BIN_DESTINATION bin)
set(LIB_DESTINATION lib)
set(PLUGIN_DESTINATION plugins)
set(PLATFORM_PLUGINS qxcb)
set(AUDIO_PLUGINS qtaudio_alsa qtmedia_pulse)

set(RUNTIME_DEPS FALSE)